# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCwbrBSLhvcIA7ymMTEtLtvxxHdyPOOq
"""

import streamlit as st
import pickle
import pandas as pd

with open("random_forest_model.pkl", "rb") as f:
    model = pickle.load(f)

st.title("Random Forest 예측기")

feature1 = st.number_input("가입 기간(월)", value=0.0)
feature2 = st.number_input("지난달 컴플레인 여부", value=0.0)
feature3 = st.number_input("선호 카테고리", value=0.0)

if st.button("예측하기"):

    X = pd.DataFrame([[feature1, feature2, feature3]], columns=["가입 기간(월)", "지난달 컴플레인 여부", "선호 카테고리"])
    pred = model.predict(X)[0]
    st.success(f"예측 결과: {pred}")
