# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCwbrBSLhvcIA7ymMTEtLtvxxHdyPOOq
"""

import streamlit as st
import pickle
import pandas as pd

with open("random_forest_model.pkl", "rb") as f:
    model = pickle.load(f)

st.title("Random Forest 예측기")

Tenure = st.number_input("Tenure", value=0)
Complain = st.number_input("Complain", value=0)
PreferedOrderCat2 = st.number_input("PreferedOrderCat2", value=0)

if st.button("예측하기"):

    X = pd.DataFrame([[Tenure, Complain, PreferedOrderCat2]], columns=["Tenure", "Complain", "PreferedOrderCat2"])
    pred = model.predict(X)[0]
    st.success(f"예측 결과: {pred}")
